name: gitoxide
adopt-info: gitoxide
summary: gitoxide is an implementation of git written in Rust
description: |
    gitoxide is an implementation of git written in Rust for developing future-proof applications 
    which strive for correctness and performance while providing a pleasant and unsurprising 
    developer experience.
    gitoxide provides the gix and ein binaries for use on the command-line to allow experimentation
    with key features like fetch and clone, and to validate the usability and control of the API
    offered by the gix crate.
    gitoxide aspires to be a production-grade server implementation and the ein binary aspires to
    become the default way to interact with git repositories. 
    
    To run it from your terminal, type: `gix` or `ein` to access binaries in the `gitoxide` suite
    
license: Apache-2.0

base: core20
grade: stable
confinement: strict
compression: lzo

apps:
  gitoxide:
    command: bin/gix
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
  
  ein:
    command: bin/ein
    environment:
      PATH: $SNAP/bin/:$PATH       
    plugs:
      - network
      - home
   
parts:
  gitoxide:
    source: https://github.com/Byron/gitoxide
    source-type: git
    plugin: rust
    after: [rustup]

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
    
    build-packages:
      - cmake
      
    build-packages:
      - cargo
      - rustc
      - pkg-config
      - librust-openssl-sys-dev    
      
  rustup:
    plugin: nil
    build-packages:
      - wget
    build-environment:
      - RUSTUP_HOME: $SNAPCRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $SNAPCRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $SNAPCRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $SNAPCRAFT_PART_SRC/rustup-init.sh
      chmod +x $SNAPCRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $SNAPCRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $SNAPCRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime' 
